L_SYSTEM_PRESETS = {
    # --- Classical ---
    'koch_snowflake': {
        'axiom': 'F--F--F',
        'rules': {'F': 'F+F--F+F'},
        'angle': 60.0,
        'depth': 4,
        'step': 10,
    },
    'koch_island': {
        'axiom': 'F+F+F+F',
        'rules': {'F': 'F-F+F+FFF-F-F+F'},
        'angle': 90.0,
        'depth': 2,
        'step': 10,
    },
    'crystal': {
        'axiom': 'F+F+F+F',
        'rules': {'F': 'FF+F++F+F'},
        'angle': 90.0,
        'depth': 3,
        'step': 10,
    },
    'square_snowflake': {
        'axiom': 'F--F',
        'rules': {'F': 'F-F+F+F-F'},
        'angle': 90.0,
        'depth': 4,
        'step': 10,
    },
    'vicsek': {
        'axiom': 'F-F-F-F',
        'rules': {'F': 'F-F+F+F-F'},
        'angle': 90.0,
        'depth': 4,
        'step': 10,
    },
    'levy': {
        'axiom': 'F',
        'rules': {'F': '+F--F+'},
        'angle': 45.0,
        'depth': 10,
        'step': 10,
    },
    # --- Sierpinski ---
    'sierpinski_carpet': {
        'axiom': 'YF',
        'rules': {'X': 'YF+XF+Y', 'Y': 'XF-YF-X'},
        'angle': 60.0,
        'depth': 1,
        'step': 10,
    },
    'sierpinski_lattice': {
        'axiom': 'FXF--FF--FF',
        'rules': {'F': 'FF', 'X': '--FXF++FXF++FXF--'},
        'angle': 60.0,
        'depth': 7,
        'step': 10,
    },
    'sierpinski_curve': {
        'axiom': 'F+XF+F+XF',
        'rules': {'X': 'XF-F+F-XF+F+XF-F+F-X'},
        'angle': 90.0,
        'depth': 4,
        'step': 10,
    },
    # --- Geometric ---
    'square': {
        'axiom': 'F+F+F+F',
        'rules': {'F': 'FF+F+F+F+FF'},
        'angle': 90.0,
        'depth': 3,
        'step': 10,
    },
    'tiles': {
        'axiom': 'F+F+F+F',
        'rules': {'F': 'FF+F-F+F+FF'},
        'angle': 90.0,
        'depth': 3,
        'step': 10,
    },
    'rings': {
        'axiom': 'F+F+F+F',
        'rules': {'F': 'FF+F+F+F+F+F-F'},
        'angle': 90.0,
        'depth': 2,
        'step': 10,
    },
    'cross': {
        'axiom': 'F+F+F+F',
        'rules': {'F': 'F+F-F+F+F'},
        'angle': 90.0,
        'depth': 3,
        'step': 10,
    },
    'cross_2': {
        'axiom': 'F+F+F+F',
        'rules': {'F': 'F+FF++F+F'},
        'angle': 90.0,
        'depth': 3,
        'step': 10,
    },
    'triangle': {
        'axiom': 'F+F+F',
        'rules': {'F': 'F-F+F'},
        'angle': 120.0,
        'depth': 2,
        'step': 10,
    },
    # --- Dragons ---
    'dragon': {
        'axiom': 'FX',
        'rules': {'X': 'X+YF+', 'Y': '-FX-Y'},
        'angle': 90.0,
        'depth': 8,
        'step': 10,
    },
    'terdragon': {
        'axiom': 'F',
        'rules': {'F': 'F-F+F'},
        'angle': 120.0,
        'depth': 5,
        'step': 10,
    },
    'double_dragon': {
        'axiom': 'FX+FX',
        'rules': {'X': 'X+YF+', 'Y': '-FX-Y'},
        'angle': 90.0,
        'depth': 6,
        'step': 10,
    },
    'triple_dragon': {
        'axiom': 'FX+FX+FX',
        'rules': {'X': 'X+YF+', 'Y': '-FX-Y'},
        'angle': 90.0,
        'depth': 7,
        'step': 10,
    },
    # --- Space-filling curves ---
    'peano': {
        'axiom': 'F',
        'rules': {'F': 'F+F-F-F-F+F+F+F-F'},
        'angle': 90.0,
        'depth': 2,
        'step': 10,
    },
    'peano_gosper': {
        'axiom': 'FX',
        'rules': {'X': 'X+YF++YF-FX--FXFX-YF+', 'Y': '-FX+YFYF++YF+FX--FX-Y'},
        'angle': 60.0,
        'depth': 4,
        'step': 10,
    },
    'gosper_square': {
        'axiom': 'YF',
        'rules': {
            'X': 'XFX-YF-YF+FX+FX-YF-YFFX+YF+FXFXYF-FX+YF+FXFX+YF-FXYF-YF-FX+FX+YFYF-',
            'Y': '+FXFX-YF-YF+FX+FXYF+FX-YFYF-FX-YF+FXYFYF-FX-YFFX+FX+YF-YF-FX+FX+YFY',
        },
        'angle': 90.0,
        'depth': 2,
        'step': 10,
    },
    'moore': {
        'axiom': 'LFL-F-LFL',
        'rules': {'L': '+RF-LFL-FR+', 'R': '-LF+RFR+FL-'},
        'angle': 90.0,
        'depth': 0,
        'step': 10,
    },
    'hilbert': {
        'axiom': 'L',
        'rules': {'L': '+RF-LFL-FR+', 'R': '-LF+RFR+FL-'},
        'angle': 90.0,
        'depth': 8,
        'step': 10,
    },
    'hilbert_2': {
        'axiom': 'X',
        'rules': {'X': 'XFYFX+F+YFXFY-F-XFYFX', 'Y': 'YFXFY-F-XFYFX+F+YFXFY'},
        'angle': 90.0,
        'depth': 4,
        'step': 10,
    },
    # --- Others ---
    'pentaplexity': {
        'axiom': 'F++F++F++F++F',
        'rules': {'F': 'F++F++F+++++F-F++F'},
        'angle': 36.0,
        'depth': 1,
        'step': 10,
    },
    'segment_32': {
        'axiom': 'F+F+F+F',
        'rules': {'F': '-F+F-F-F+F+FF-F+F+FF+F-F-FF+FF-FF+F+F-FF-F-F+FF-F-F+F+F-F+'},
        'angle': 90.0,
        'depth': 3,
        'step': 10,
    },
    'krishna_anklets': {
        'axiom': '-X--X',
        'rules': {'X': 'XFX--XFX'},
        'angle': 45.0,
        'depth': 3,
        'step': 10,
    },
    'plant': {
        'axiom': 'F',
        'rules': {'F': 'F-F+F'},
        'angle': 25.0,
        'depth': 5,
        'step': 10,
    },
}
